server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # ========================================================
    # React SPA routing
    # /login
    # /register
    # /dashboard
    # etc.
    # ========================================================

    location / {
        try_files $uri $uri/ /index.html;
    }

    # ========================================================
    # Static assets
    # ========================================================

    location /assets/ {
        try_files $uri =404;
    }
}